/*
 * Auto-Generated Industrial AWS IoT Core mTLS Certificates & Key
 * Target Device: SunGridNova-FB04
 * Generation Timestamp: 2026-10-08T18:01:02.504137+00:00
 * Security Standard: ECDSA SECP256R1 / SHA256
 */

#pragma once

#ifndef AWS_IOT_CERTS_H
#define AWS_IOT_CERTS_H

/* Amazon Root CA 1 Certificate */
static const char *AWS_ROOT_CA_CERT =
"-----BEGIN CERTIFICATE-----\n"
"MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
"ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
"b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
"MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
"b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
"ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
"9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
"IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
"VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
"93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
"jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
"AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
"A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
"U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
"N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
"o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
"5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
"rqXRfboQnoZsG4q5WTP468SQvvG5\n"
"-----END CERTIFICATE-----\n";

/* Dynamic Client Device X.509 Certificate */
static const char *AWS_CLIENT_CERT =
"-----BEGIN CERTIFICATE-----\n"
"MIICWDCCAf+gAwIBAgIUdiICo3hm8Xnaz873l5ENAKIerDwwCgYIKoZIzj0EAwIw\n"
"gaExCzAJBgNVBAYTAklOMRIwEAYDVQQIDAlLYXJuYXRha2ExEjAQBgNVBAcMCUJl\n"
"bmdhbHVydTEjMCEGA1UECgwaU3VuR3JpZE5vdmEgRW5lcmd5IFN5c3RlbXMxKjAo\n"
"BgNVBAsMIUluZHVzdHJpYWwgSW52ZXJ0ZXIgU2VjdXJpdHkgQ29yZTEZMBcGA1UE\n"
"AwwQU3VuR3JpZE5vdmEtRkIwNDAeFw0yNjAxMDEwMDAwMDBaFw00MDAxMDEwMDAw\n"
"MDBaMIGhMQswCQYDVQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQH\n"
"DAlCZW5nYWx1cnUxIzAhBgNVBAoMGlN1bkdyaWROb3ZhIEVuZXJneSBTeXN0ZW1z\n"
"MSowKAYDVQQLDCFJbmR1c3RyaWFsIEludmVydGVyIFNlY3VyaXR5IENvcmUxGTAX\n"
"BgNVBAMMEFN1bkdyaWROb3ZhLUZCMDQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\n"
"AASdlaQZOtA4IOkNyTQQCUOHrgDt4nN7NZfmZR/EVyOLxaIeJ4sERXvuaYmepoUb\n"
"VQ7hrtTfY4MoAX3LHQqKywzMoxMwETAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49\n"
"BAMCA0cAMEQCIFhp9BCpxTHlboQzOlY0deQlwGN0wHhrECHNIKy2frmbAiAJzKxP\n"
"E+NHjluZXU9KE1UNXMAYEOgIlhrWLrxe+NIu1w==\n"
"-----END CERTIFICATE-----\n";

/* Dynamic Client Device SECP256R1 EC Private Key */
static const char *AWS_CLIENT_KEY =
"-----BEGIN EC PRIVATE KEY-----\n"
"MHcCAQEEIJ8j82uwXuMdoVT6rwyR1HbcVE9tvTfG7mUIdUaTS5+AoAoGCCqGSM49\n"
"AwEHoUQDQgAEnZWkGTrQOCDpDck0EAlDh64A7eJzezWX5mUfxFcji8WiHieLBEV7\n"
"7mmJnqaFG1UO4a7U32ODKAF9yx0KissMzA==\n"
"-----END EC PRIVATE KEY-----\n";

#endif /* AWS_IOT_CERTS_H */
